# Generated by Django 6.0.2 on 2026-02-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_reg_no',
            field=models.CharField(default='0000', max_length=12, unique=True),
        ),
    ]
